// Single source of truth for the 5 home-seller situations served by VP Buys Homes.
// Used by:
//   - `app/situations/[situation]/page.tsx`        (situation pillar pages)
//   - `app/areas/[city]/[situation]/page.tsx`      (city × situation intersection pages)
//   - `app/situations/page.tsx`                    (situation directory hub)
//   - `app/areas/[city]/page.tsx`                  (Situations grid linking out)
//   - `app/sitemap.ts`                             (URL generation)
//
// State-level (Georgia) facts only. Per-pairing copy lives in
// `lib/situations/<slug>-content.ts`.
//
// Statutes are cited from OCGA primary text (verified via codes.findlaw.com,
// ga.elaws.us, and law.georgia.gov as of 2026-04). Industry-customary
// timelines (e.g. "Day 16 late fee", "Day 90 referral") are intentionally
// EXCLUDED — they are not in statute and could be fabricated if cited.

export type SituationSlug =
  | 'foreclosure'
  | 'divorce'
  | 'probate'
  | 'tired-landlord'
  | 'tax-liens'

export type Situation = {
  slug: SituationSlug
  label: string                  // "Foreclosure"
  shortLabel: string             // "Foreclosure" (for breadcrumbs/cards — short form)
  searchVerb: string             // headline/SEO verb: "Stop", "Settle", "Sell Through", etc.
  triggers: string[]             // 3 emotional triggers (informs body copy)
  objections: string[]           // 3 cash-buyer red flags this seller worries about
  whatWeDo: string[]             // 4-5 bullets on what a legitimate cash buyer offers
  ocgaRefs: { code: string; summary: string }[]   // verified GA statute citations
  pillarLead: string             // 2-3 sentence intro for /situations/[slug] page
  pillarBody: string[]           // long-form essay paragraphs for /situations/[slug] page (1,500-2,200 words)
}

export const SITUATIONS: Situation[] = [
  {
    slug: 'foreclosure',
    label: 'Foreclosure',
    shortLabel: 'Foreclosure',
    searchVerb: 'Stop',
    triggers: [
      'Dread that neighbors and coworkers will see the foreclosure ad in the local legal-organ newspaper',
      'Panic about being physically removed from the home after sale day with nowhere else to go',
      'Shame about telling a spouse, parents, or kids that the family is losing the house',
    ],
    objections: [
      'Wholesalers who tie the property up under contract and never actually close, leaving the seller worse off',
      'Lowball offers timed to the seller\'s panic, knowing they have no time to shop',
      'Out-of-state buyers who do not know the local courthouse, lender\'s reinstatement window, or attorneys handling the file',
    ],
    whatWeDo: [
      'Coordinate a payoff request directly with the lender\'s loss-mitigation department',
      'Close before the first-Tuesday courthouse sale date when title is clear',
      'Pay standard closing costs and existing arrears as part of the purchase price',
      'Refer you to a HUD-approved housing counselor or foreclosure attorney before you sign',
    ],
    ocgaRefs: [
      { code: 'OCGA § 44-14-162', summary: 'Sales under power must be advertised in the county where the property sits, once a week for four weeks before the sale.' },
      { code: 'OCGA § 44-14-162.2', summary: 'Lender must mail the borrower written notice of the sale by registered or certified mail no later than 30 days before the proposed foreclosure sale date.' },
      { code: 'OCGA § 44-14-162.3', summary: 'The 30-day notice requirement cannot be waived in the security deed.' },
      { code: 'OCGA § 9-13-161', summary: 'Sheriff\'s and foreclosure sales are held on the first Tuesday of each month, between 10 AM and 4 PM, at the county courthouse.' },
    ],
    pillarLead: 'Georgia is a non-judicial foreclosure state — once the lender mails the 30-day notice and starts the four-week newspaper advertisement, the courthouse sale comes fast. A sale before that date is often still possible, but the timeline is tight and lender-driven.',
    pillarBody: [
      'Georgia\'s non-judicial foreclosure is faster than most states realize. There is no judge, no court hearing, no lawsuit filed. The lender\'s attorney does the paperwork. The homeowner often does not understand what is happening until the timeline has already started.',
      'The 30-day notice under OCGA § 44-14-162.2 is the formal trigger. It must be mailed by certified or registered mail, return receipt requested. The letter has to identify the entity with full authority to negotiate or modify the loan — a requirement the General Assembly added because servicers were sometimes unclear about who actually had decision-making authority over a borrower\'s file.',
      'The four-week newspaper advertising under OCGA § 44-14-162 runs in the county\'s designated legal-organ newspaper. Each Georgia county has a specific paper — the Statesboro Herald in Bulloch, the Effingham Herald in Effingham, the Savannah Morning News in Chatham, the Metter Advertiser in Candler, the Forest-Blade in Emanuel, the Claxton Enterprise in Evans, and The Advance in Toombs. By the second week of advertising, neighbors and family who read the paper online may have already seen the listing.',
      'The sale itself happens on the first Tuesday of every month, between 10 AM and 4 PM, on the courthouse steps of the county where the property sits. OCGA § 9-13-161 sets these hours. If the first Tuesday falls on New Year\'s Day or July 4, the sale moves to Wednesday. The sale runs by public outcry — a legal term that means open auction in front of the courthouse. Buyers physically attend.',
      'That timing — 30-day notice, four-week ad, first-Tuesday sale — means the typical Georgia foreclosure has a window of roughly 30 to 35 days between when the certified-mail notice arrives and when the gavel falls. That is short. Many homeowners spend the first two weeks deciding whether to act, the next two weeks trying to scramble for funds, and discover late that bank lending and traditional listings cannot move on this timeline.',
      'During those weeks, a homeowner has several options worth considering before selling. Loan modification through the servicer — the entity identified in the 30-day notice — is often available, even on tight timelines. A HUD-approved housing counselor, free of charge, can sometimes negotiate a modification or repayment plan that the homeowner could not on their own. A foreclosure-defense attorney can sometimes find procedural defects in the notice, the advertisement, or the chain of authority that justify pausing the sale through court action. None of these are guaranteed to work, but each deserves a phone call before signing a sale contract.',
      'When none of those alternatives fit, a sale before sale day is often the best remaining option. A traditional listing rarely closes inside a 30-day notice window because of inspection contingencies, appraisal requirements, and buyer financing. A cash sale skips those steps. The lender\'s payoff letter is the bottleneck — and a buyer who knows how to coordinate directly with the loss-mitigation department can usually pull a clean payoff figure within a few business days.',
      'A cash sale before sale day pays off the lender at closing. The 30-day notice is canceled by the payoff. The newspaper advertisement stops at the next print cycle. The sale never happens. The homeowner walks away with whatever equity remained, and any second mortgages, HELOCs, or other liens have to be paid off (or short-paid with creditor consent) at the same closing for clear title.',
      'When a sale before sale day does not happen, the property goes to the courthouse steps. The high bidder receives a deed under power of sale. That deed transfers ownership but does not by itself extinguish all junior liens. If the lender is the high bidder and later wants to pursue the borrower personally for any deficiency on the loan, OCGA § 44-14-161 requires a separate court confirmation proceeding within 30 days of the sale.',
      'After the sale, the displaced homeowner becomes a tenant at sufferance — a legal term meaning their right to occupy has ended but they have not yet been formally removed. To physically remove the homeowner, the new owner has to file a separate dispossessory action under OCGA § 44-7-50. That dispossessory takes weeks. Many former homeowners stay in the house during that period.',
      'There are out-of-state cash-buying operations that advertise heavily during foreclosure season in every Georgia market. A few patterns mark them. First, they sometimes do not know which county-specific newspaper handles legal notices. Ask any potential buyer which paper your foreclosure ad has to run in. A real local operator names the right paper without hesitation. A wholesaler advertising from Phoenix or Charlotte will often hesitate.',
      'Second, they sometimes sign contracts and then try to assign them to a real buyer. This is wholesaling. If the assignment fails (which happens often in foreclosure-stage files), the original homeowner ends up further along in the foreclosure timeline with less time to find another option. Asking up front whether the buyer is closing on its own funds, or assigning the contract to another buyer, is a fair question. The answer matters.',
      'Third, they sometimes back out at the last minute when the title work surfaces something they did not anticipate — a junior lien, a chain-of-title defect, a code violation, a Historic-District encumbrance. A real buyer who has worked the local market knows what kinds of complications come with which kinds of properties and prices accordingly.',
      'A legitimate local cash buyer for a Georgia foreclosure file generally does several things consistently. They pull a real payoff figure from the lender\'s loss-mitigation department before signing a contract. They close through a local closing attorney who works the relevant county\'s recording desk regularly. They pay standard closing costs — no commissions, no listing fees, and the costs that traditionally come out of a seller\'s check are folded into the offer. They coordinate with junior lienholders, HOAs, tax commissioners, and any other interest-holders who need to be paid off at the same closing for clear title. And they refer the homeowner to a HUD-approved housing counselor or a Georgia foreclosure-defense attorney before contracting, when the facts suggest a better path. A buyer who never refers is a buyer whose own pipeline is more important than the seller\'s actual situation.',
      'The decision to sell is not simply about the offer price. A foreclosure-stage seller is comparing the cash offer against several alternatives: the courthouse-steps sale outcome (which usually nets the seller nothing); a successful loan modification (which keeps the home but extends the debt); a short sale negotiated with the lender (which sometimes preserves credit but takes time); or a foreclosure-defense court action (which pauses but does not necessarily prevent the sale). Each alternative has different math and different timelines.',
      'For most homeowners with a real-time foreclosure file, the cash sale is the cleanest exit. Equity, if any, transfers to the seller. The mortgage is paid off cleanly. The 30-day notice is canceled. The credit damage from the foreclosure itself is limited — though late payments still show on the report, the foreclosure sale itself does not. The homeowner moves forward on their own timeline rather than the lender\'s.',
      'Cash offers are below retail market value. That tradeoff is real. The discount reflects the cost of repairs the property may need, the holding time before resale, and the speed and certainty of cash. A homeowner with months of runway, equity, and a property in good condition might get more by listing traditionally. A homeowner with weeks of runway, no equity buffer, or a property that needs work usually nets more from a cash sale than from any other path.',
      'The numbers worth knowing before contracting: the lender\'s actual payoff figure (different from the principal balance), the redemption-style cost of any junior liens, any back property taxes owed to the county tax commissioner, and the fair-market value of the property in its current condition. A real cash offer accounts for all four. A wholesale offer often only accounts for the principal and ignores the rest until the title work surfaces it.',
      'For homeowners with a Georgia foreclosure file in any of our service-area counties — Bulloch, Effingham, Chatham, Candler, Emanuel, Evans, or Toombs — the early call matters. Two weeks before sale day is plenty of time. One week is workable if the lender responds quickly. Inside three days, the timeline gets very tight. The phone call costs nothing and produces a real number.',
      'When the 30-day notice arrives, the first 48 hours matter. Read the letter carefully — it identifies the entity with authority to negotiate, includes the proposed sale date, and specifies how to contact loss mitigation. Save the envelope with the postmark. Photograph everything. Call the loss-mitigation department before you call anyone else. They are often able to provide reinstatement quotes, modification options, or deferment programs that buy weeks of additional time. Even if those options do not ultimately work, they give you better information for whatever decision comes next.',
      'Verifying a Georgia cash buyer takes about three phone calls. First, confirm the buyer is actually the buyer — ask whether the contract is being assigned to another party. A real cash buyer holds funds and closes themselves. Second, confirm the closing attorney is local to your county — not based in another state. A closing attorney unfamiliar with your county\'s recording desk slows the process. Third, check the Georgia Secretary of State\'s business registry to confirm the buyer is registered as a Georgia corporation or LLC. Out-of-state shell companies sometimes appear as recently-registered entities or fail to register at all. Asking these questions does not insult a real buyer; it filters out the wholesalers.',
    ],
  },
  {
    slug: 'divorce',
    label: 'Divorce',
    shortLabel: 'Divorce',
    searchVerb: 'Sell Through',
    triggers: [
      'Fear that the ex-spouse will block the sale or refuse to sign at closing',
      'Stress that mortgage payments are still due while one spouse has already moved out',
      'Anxiety that delay reduces both sides\' shares because of accruing interest, taxes, and HOA dues',
    ],
    objections: [
      'Buyer who does not understand the divorce decree language about who has authority to sell',
      'Buyer who pressures one spouse to sign without coordinating with the other or their attorneys',
      'Wholesale-style "we\'ll just take a deed" offer that ignores the still-active mortgage and tax-basis issues',
    ],
    whatWeDo: [
      'Work with both spouses\' attorneys so the closing matches the decree or pending order',
      'Fund a clean payoff of the mortgage so neither spouse keeps housing debt after the divorce',
      'Time closing around court hearings rather than against them',
      'Pay standard closing costs without renegotiating after a settlement is signed',
    ],
    ocgaRefs: [
      { code: 'OCGA § 19-5-2', summary: 'A petitioner for divorce must be a bona fide resident of Georgia for six months before filing.' },
      { code: 'OCGA § 19-5-13', summary: 'The court divides marital property in accordance with the law and the rules of equity (equitable distribution — not always 50/50).' },
      { code: 'OCGA § 19-3-9', summary: 'Each spouse\'s separate (non-marital) property remains separate during the marriage.' },
    ],
    pillarLead: 'Georgia uses equitable distribution, not community property. Whether the home is marital or separate, who can sign at closing, and how proceeds get split are controlled by the divorce decree or pending court order — not by who is on the deed.',
    pillarBody: [
      'Selling a house during a Georgia divorce is a different kind of real-estate transaction. It usually involves two people who do not entirely agree, two attorneys negotiating against each other, and a court order or settlement agreement that controls who has authority to sign at closing.',
      'Georgia is an equitable distribution state, governed by OCGA § 19-5-13. That phrase — equitable distribution — is often misunderstood. It does not mean fifty-fifty. It means the court divides marital property in accordance with the law and the rules of equity. Fair, given each spouse\'s contributions, conduct during the marriage, and reasonable needs going forward.',
      'Equitable distribution is different from the community property system used in nine other U.S. states. In a community property state, marital assets are typically split equally regardless of contribution. In Georgia, contribution and conduct can move the math significantly. A spouse who contributed more financially or to property maintenance may receive more. A spouse whose conduct (such as adultery or reckless dissipation of marital assets) damaged the marriage may receive less. The judge or the settlement agreement decides the specifics.',
      'The marital home is usually treated as marital property — even when only one spouse is on the deed, even when one spouse owned the property before the marriage. OCGA § 19-3-9 says each spouse\'s separate property remains separate. But "transmutation" can shift property from separate to marital over time, when marital funds, marital labor, or shared use change the property\'s character. A house one spouse owned before marriage that the couple lived in for fifteen years, paid mortgage on with joint income, and improved with shared work has often transmuted into marital property — at least in part.',
      'The basic divorce process in Georgia starts with one spouse meeting the residency requirement of OCGA § 19-5-2 — a bona fide Georgia resident for six months before filing. The petitioner files in the Superior Court of the county where the responding spouse resides (or, in some cases, where the petitioner resides if the other spouse has left the state). The respondent has 30 days to file an answer.',
      'A temporary hearing usually follows. This is where the court addresses immediate practical issues — who lives in the marital home, who pays the mortgage during the case, whether either spouse can sell or refinance assets while the case is pending, what custody and support arrangements apply. Some Superior Court judges issue standing orders that automatically restrict asset transfers in pending cases. These standing orders matter for any sale of the marital home during the divorce.',
      'Discovery, mediation, or contested hearings follow the temporary phase. Most contested Georgia divorces settle before trial. Mediation is often required by the local Superior Court. The pace varies by county and judge — Eastern Judicial Circuit (Chatham) and Atlantic Judicial Circuit (Liberty, Evans, others) tend to have busier dockets than the rural Middle Judicial Circuit or Ogeechee Judicial Circuit.',
      'The final divorce decree controls everything about the marital home: whether to sell it, refinance into one spouse\'s name, transfer the deed to one spouse with offsetting payments, or partition it with court oversight. The decree also controls how proceeds from any sale are split. Some decrees specify percentages. Some specify offsetting cash equalizers. Some require sale within a specified period, with proceeds held in escrow until the decree\'s other obligations get reconciled.',
      'When the decree directs a sale, the closing has to match the decree language. Title companies and closing attorneys generally require both spouses to sign at closing while the marriage is intact — and require the appropriate spouses with authority under the decree once the divorce is final. A sale that does not match the decree creates a title defect that can surface years later.',
      'Some sales happen during the divorce, before the final decree. These usually require either both spouses\' written consent in a settlement agreement filed with the court, or a temporary order from the Superior Court explicitly authorizing the sale. Without one of those, a closing during pendency may violate any standing order and create real legal risk for both spouses and the buyer.',
      'The proceeds from a marital-home sale during pendency are usually held in escrow until the final decree spells out how they get distributed. That escrow can be at the closing attorney\'s trust account, in a court registry, or in a joint account requiring both spouses\' signatures. The decree at the end resolves the holding.',
      'For a buyer, a Georgia divorce-stage sale requires reviewing the decree, settlement agreement, or temporary order before signing a contract. The wrong paperwork at closing creates title-insurance problems and can stall the sale at the table. A real-estate attorney should review the controlling documents before any contract is signed.',
      'Out-of-state cash-buying operations sometimes try to skip this review. They sign contracts based on what one spouse tells them and discover the marital-property issue at closing. The result is usually a delayed closing, a renegotiated price, or a failed transaction.',
      'A legitimate cash buyer for a Georgia divorce-stage marital home generally does several things consistently: confirms the controlling court documents before contracting, coordinates with both spouses\' family-law attorneys, accommodates remote signing logistics for spouses who have already moved, funds a clean mortgage payoff so neither spouse keeps marital housing debt after the divorce, and times the closing around hearing dates rather than against them.',
      'For some divorces, the marital home is best refinanced by one spouse rather than sold. A spouse who can qualify for a new mortgage in their own name, and who wants to keep the property, may be able to buy out the other spouse through refinance. The refinance pays off the old joint mortgage and provides a cash-out portion that funds the equitable share owed to the departing spouse. This is sometimes simpler than a sale to a third party — but it requires the staying spouse to qualify on their own income.',
      'When neither spouse can or wants to keep the property, a sale becomes the path. A traditional listing through a real-estate agent often produces the highest sale price — but it also takes time, requires ongoing maintenance and showings during a stressful period, involves inspection-and-appraisal contingencies, and depends on the buyer\'s financing closing on schedule. Each of those pieces can stall around a divorce timeline.',
      'A cash sale is faster, more certain, and does not depend on lender financing. The tradeoff is price — cash offers are below retail. For a divorce where both spouses want a clean exit, where the home needs work that neither spouse wants to fund, or where the divorce timeline is tight, the cash sale often nets more (after factoring time, ongoing carry costs, and uncertainty) than a traditional listing would.',
      'The tax side of a marital-home sale deserves a CPA conversation before contracting. The IRC § 121 home-sale exclusion ($250,000 single / $500,000 joint) can apply if certain ownership and use tests are met. Capital gains beyond the exclusion get taxed. If one spouse received the property in the divorce and then sold it later, basis calculations follow specific IRS rules. A CPA can review your specific situation — that conversation is usually worth more than its cost.',
      'Joint debt after divorce is a common problem. If the mortgage stays in both names after the decree, both spouses remain personally liable to the lender — even if the decree assigns responsibility to one spouse. A lender does not have to honor a divorce decree\'s reallocation of mortgage liability without an actual refinance. A clean cash sale during or after the divorce eliminates this problem by paying off the joint mortgage entirely.',
      'For sellers in any of our Southeast Georgia service-area counties — Bulloch, Effingham, Chatham, Candler, Emanuel, Evans, or Toombs — the divorce-stage sale process follows the same Georgia framework. The local courthouse, judges, and pace differ. The legal substance is the same. The cash-sale option is available at any stage where the appropriate court documents authorize the sale.',
      'Some Georgia counties have automatic standing orders that take effect the moment a divorce is filed. These orders typically restrict either spouse from selling, refinancing, transferring, encumbering, or substantially diminishing marital assets without court approval or the written consent of the other spouse. Standing orders are different from temporary orders. They apply automatically to all newly-filed divorce cases in those counties. If your case is filed in a county with standing orders, the marital-home sale conversation has to start by reading the order carefully — your attorney will know whether one applies to your specific case.',
      'Real estate is not the only marital asset that gets divided in a Georgia divorce. Retirement accounts (401(k), pension, IRA) get divided through a Qualified Domestic Relations Order, or QDRO — a separate court order distinct from the divorce decree. Bank accounts, vehicles, businesses, and personal property each have their own division mechanisms. The marital home is usually the largest single asset on the table, but the closing on the home does not by itself complete the division. A family-law attorney coordinates the entire division across all asset types, with the marital-home sale being one piece.',
      'Four common marital-home outcomes are worth understanding. First, sale and split — both spouses sign, the home sells to a third party, proceeds get split per the decree. Second, refinance and buyout — one spouse refinances into their own name and pays the other an equitable share. Third, deed-only transfer with offsetting payments — one spouse receives the deed, with offsetting allocations of other marital assets to balance the equity. Fourth, deferred sale — both spouses retain ownership through the divorce, with the property to be sold at a future trigger event such as children reaching majority. Each outcome has different tax, lender, and timing implications.',
    ],
  },
  {
    slug: 'probate',
    label: 'Probate / Inherited Property',
    shortLabel: 'Probate',
    searchVerb: 'Sell',
    triggers: [
      'Grief mixed with paperwork overwhelm — dozens of probate forms feel impossible while still planning a funeral',
      'Sibling tension over who should sell the house and at what price',
      'Worry that a vacant inherited house will be vandalized, hit with a code violation, or insurance-canceled while probate drags on',
    ],
    objections: [
      'Buyer who wants to close before letters testamentary or letters of administration are issued, which clouds title',
      'Buyer who bypasses the probate court\'s required notices and approvals',
      'Buyer who pressures one heir to sign without confirming the others have agreed',
    ],
    whatWeDo: [
      'Wait for letters testamentary, letters of administration, year\'s support order, or a § 53-2-40 no-administration-necessary order before closing',
      'Coordinate with the probate attorney handling the estate',
      'Make the offer to the estate or all heirs collectively, not to one heir alone',
      'Carry the holding costs (insurance, utilities) under a longer due-diligence window when probate is mid-stream',
    ],
    ocgaRefs: [
      { code: 'OCGA § 53-2-40', summary: 'When the decedent died intestate, no representative is appointed, and heirs agree on the division, the court can declare "no administration necessary."' },
      { code: 'OCGA § 53-3-1', summary: 'Surviving spouse and minor children are entitled to year\'s support — property taken from the estate for 12 months of support and maintenance.' },
      { code: 'OCGA § 53-3-5', summary: 'A petition for year\'s support must be filed within two years of the decedent\'s date of death.' },
      { code: 'OCGA § 53-5-21', summary: 'Solemn-form probate procedure — when all heirs file an assent, letters testamentary may issue without further delay.' },
    ],
    pillarLead: 'Selling an inherited Georgia home rarely requires full probate from start to finish. A no-administration-necessary order, a year\'s support petition, or a quick solemn-form probate with all heirs assenting can each transfer title — but each requires the right paperwork at the probate court.',
    pillarBody: [
      'Probate is the legal process for handling someone\'s affairs after they die. In Georgia, the Probate Court in each county has authority over wills, estates, year\'s support petitions, and certain other matters. The probate process determines who has legal authority to manage and transfer the deceased person\'s assets — including any real estate they owned.',
      'Selling an inherited Georgia home during or after probate requires the right paperwork. Without that paperwork, no title company will issue title insurance, and no closing attorney will record a deed. The right paperwork depends on what the deceased person left behind and what the heirs decide.',
      'Several legal paths can produce the right paperwork. They are not interchangeable. Picking the wrong one (or skipping the process entirely) creates title problems that surface only when the property is sold years later.',
      'Solemn-form probate is the most common path when there is a will and an executor. The executor named in the will petitions the Probate Court of the county where the deceased lived. Heirs are notified or sign assents. If all heirs sign assents, OCGA § 53-5-21 lets letters testamentary issue without further delay. Without assents, heirs are personally served and at least 10 days pass before letters can issue.',
      'Letters testamentary are the document that gives the executor legal authority to act on behalf of the estate — including selling real property. With letters in hand, the executor can sign a contract, sign a deed at closing, and convey title to a buyer. Without letters, no sale can close.',
      'When there is no will, the family petitions for letters of administration. An administrator (often a surviving spouse, adult child, or other interested party) is appointed by the Probate Court after a petition with notice to other interested parties. Letters of administration give the administrator the same kind of authority that letters testamentary give an executor — including authority to sell real estate.',
      'Year\'s support is a uniquely Georgia mechanism under OCGA § 53-3-1. It lets a surviving spouse and minor children claim property from the estate sufficient to support them for 12 months from the date of death. Year\'s support often includes the family home. Once granted by the Probate Court, year\'s support transfers title to the home cleanly and can have priority over most creditors. The petition must be filed within 2 years of the date of death (OCGA § 53-3-5).',
      'For some estates, a no-administration-necessary order under OCGA § 53-2-40 can skip full probate. This is available when the deceased died intestate (without a will), no personal representative has been appointed, the estate has no debts (or all creditors consent), and the heirs have agreed on the division. The Probate Court can issue an order declaring no administration necessary, which lets the heirs divide and sell the property without going through full probate.',
      'Each of these paths has different paperwork requirements, different waiting periods, and different costs. A first consultation with a Georgia probate attorney is generally inexpensive and is the right first step. The attorney reviews the will (if any), identifies the heirs, lists the estate\'s assets and debts, and recommends the appropriate path.',
      'The actual timeline of a Georgia probate varies widely. Solemn-form probate with all heirs assenting can move relatively quickly through the Probate Court — sometimes within weeks. Letters of administration take longer because of the notice period and potential contests. Contested probates, complex estates with multiple properties or business interests, or estates with disputed wills can take many months or longer. The Probate Court of the county where the deceased lived controls the calendar.',
      'Some probate courts move faster than others. Smaller-county Probate Courts (Candler, Evans, Toombs) sometimes process clean estates within weeks. Busier courts (Chatham) can take longer simply because of caseload. The probate attorney handling the estate will have a sense of current timing.',
      'During probate, the estate has obligations — paying property taxes, maintaining insurance on real property, securing assets, and complying with Probate Court orders for accounting. A vacant inherited home accrues holding costs (utilities, insurance, basic upkeep) every month probate is open. For estates that hold property through extended probate, those holding costs add up.',
      'Selling an inherited home before probate is generally not possible — the heirs do not yet have legal authority to convey title. Some specific exceptions exist. Property held in joint tenancy with right of survivorship transfers automatically to the surviving owner without probate. Property held in a properly drafted revocable living trust passes through the trust without probate. Property subject to a transfer-on-death deed (a specific instrument under Georgia law) transfers without probate. Other situations almost always require some Probate Court action first.',
      'When the probate paperwork is in hand — letters testamentary, letters of administration, year\'s support order, or no-administration-necessary order — the property can be sold. The closing follows the regular real-estate process, with the matching probate document attached to the closing package. The deed transfers title from the estate (or the year\'s support recipient) to the buyer.',
      'For inherited Georgia homes with multiple heirs, all heirs generally have to agree to a sale unless the will specifically gives the executor sole authority to sell or unless year\'s support has transferred sole title to the surviving spouse. When heirs disagree, options narrow. One heir cannot force the others to sell informally. A petition for partition in Superior Court can sometimes resolve the dispute, but partition is slower and more expensive than a voluntary sale.',
      'Inherited properties often come with specific complications: deferred maintenance, outdated systems, full of personal belongings, decades of family history, multi-generational expectations. A traditional listing requires a clean property, working systems, and showings — none of which an estate with active probate is well-positioned to deliver. A cash buyer who buys as-is removes those requirements.',
      'Out-of-state cash-buying operations sometimes try to close inherited-property sales without the probate paperwork. This is a serious problem. Without letters testamentary, letters of administration, year\'s support order, or a § 53-2-40 order, the seller has no authority to convey title. A title company will not insure such a sale. A closing attorney should not record such a deed. If a sale somehow closed without the right paperwork, the buyer\'s title would be defective — and the issue would surface when they later tried to sell or finance the property.',
      'A legitimate cash buyer for a Georgia inherited home generally does several things: waits for the right Probate Court paperwork before closing, coordinates with the probate attorney handling the estate, makes the offer to the estate or all heirs collectively (not to one heir privately), accepts properties as-is with belongings still in place, and accommodates extended due-diligence periods when probate takes time.',
      'The decision about whether to sell an inherited home is not always financial. Some families want to keep a multigenerational property even when keeping it makes no financial sense. Some heirs split sale proceeds for retirement, college funds, or to settle estate creditors. Some estates have to sell because nobody wants the property and nobody wants to pay the holding costs. Each situation is specific.',
      'The tax treatment of inherited property is generally favorable. Heirs receive a "stepped-up basis" — meaning the property\'s tax basis is the fair market value on the date of death, not the deceased person\'s original purchase price. If the property is sold for an amount close to that stepped-up basis, the capital gain (and resulting tax) is small or zero. If the property is held for years after inheritance and rented or appreciated, the math gets more complicated. A CPA can review specific facts.',
      'For Georgia heirs in any of our service-area counties — Bulloch, Effingham, Chatham, Candler, Emanuel, Evans, or Toombs — the early call matters. Probate moves on its own schedule. The earlier we know about an inherited property, the longer we can be patient with the Probate Court timeline rather than rushing it.',
      'In the first 30 days after a Georgia homeowner dies, several practical steps usually matter. Secure the property — change locks if appropriate, confirm homeowner\'s insurance remains in place, address any immediate physical hazards. Locate the original will if there is one. Identify the heirs — including any children (including step-children if named in the will) and any surviving spouse. Identify the deceased\'s debts as best you can — credit cards, mortgages, medical bills, and tax obligations. List the assets, including the home, vehicles, retirement accounts, and bank accounts. Most of this information is gathered before a probate attorney is consulted, so the consultation can be productive.',
      'Wills, trusts, and intestate succession are different mechanisms with different consequences. A will is a written document that specifies the deceased\'s wishes for asset distribution; it must be probated through the Probate Court to take effect on real estate. A trust — particularly a revocable living trust — holds assets during the grantor\'s lifetime and passes them through the trust\'s terms without probate. Intestate succession kicks in when there is no will: Georgia\'s OCGA § 53-2 specifies how assets pass to surviving spouse, children, and other heirs. The path through the Probate Court differs depending on which of these applies.',
      'Some Georgia estates are insolvent — meaning total debts exceed total assets. In an insolvent estate, the personal representative pays creditors in priority order set by Georgia law (OCGA § 53-7-40), and heirs may receive nothing. Selling the home may still be necessary to pay creditors. Talking to a probate attorney early is especially important when the estate looks like it might be insolvent — the attorney can advise on whether to formally administer the estate or whether to disclaim and let creditors pursue assets directly.',
    ],
  },
  {
    slug: 'tired-landlord',
    label: 'Tired Landlord',
    shortLabel: 'Tired Landlord',
    searchVerb: 'Exit',
    triggers: [
      'Burnout from middle-of-the-night plumbing calls and chasing late rent every month',
      'Resentment that the property "owns the landlord," not the other way around',
      'Fear of the capital-gains and depreciation-recapture tax bill on a long-held rental',
    ],
    objections: [
      'Buyer who insists the landlord evict the tenant first — adding 30–60+ days the seller does not want',
      'Lowball offer that ignores the property is rented at market and producing income',
      'Buyer who does not understand 1031 timing and will not accommodate a qualified intermediary',
    ],
    whatWeDo: [
      'Buy the property as-is, with the tenant in place if the lease is intact',
      'Close around 1031 timing if the seller has set up a qualified intermediary',
      'Pay standard closing costs without asking the seller to fund repairs',
      'Refer the seller to a CPA before closing to confirm tax treatment',
    ],
    ocgaRefs: [
      { code: 'OCGA § 44-7-50', summary: 'Landlord must demand possession from the tenant before filing a dispossessory affidavit.' },
      { code: 'OCGA § 44-7-53', summary: 'Tenant has seven days from service of the dispossessory affidavit to answer; if the seventh day is a weekend or holiday, the deadline is the next business day.' },
      { code: 'OCGA § 44-7-55', summary: 'A writ of possession becomes effective seven days after judgment.' },
      { code: 'OCGA § 44-7-34', summary: 'Within 30 days after obtaining possession of the premises, the landlord must return the security deposit minus any itemized lawful deductions.' },
    ],
    pillarLead: 'Selling a Georgia rental is not the same as selling a primary residence. The IRC § 121 home-sale exclusion usually does not apply, depreciation must be recaptured, and a 1031 exchange has hard 45-day and 180-day deadlines that most buyers will not coordinate around.',
    pillarBody: [
      'Selling a Georgia rental property is not the same kind of transaction as selling a primary residence. The IRC § 121 home-sale exclusion that protects up to $250,000 ($500,000 for joint filers) of primary-residence gains usually does not apply to rentals. The depreciation taken over years of rental ownership has to be recaptured at sale. The tenant\'s lease usually survives the sale. The ongoing landlord obligations transfer to the buyer.',
      'For Georgia landlords who are tired of rental ownership, the exit options are narrower than they appear. A traditional listing requires the cooperation of either an existing tenant (for showings, inspections, and possibly vacating the property) or an empty unit (which usually means waiting for a lease to end or running a Georgia dispossessory). Either path adds time. Many tired landlords end up holding longer than they want because the conventional exit path is more disruptive than continuing to rent.',
      'Georgia\'s landlord-tenant framework lives in OCGA Title 44, Chapter 7. The relevant statutes for landlords thinking about exiting include OCGA § 44-7-50 (demand for possession before dispossessory), § 44-7-53 (tenant\'s seven-day answer period after service), § 44-7-55 (writ of possession effective seven days after judgment), and § 44-7-34 (security deposit return within 30 days after the landlord obtains possession, less itemized lawful deductions).',
      'The Georgia dispossessory process — used when a landlord needs to remove a non-cooperative tenant — runs through the magistrate court of the county where the property is. After demanding possession, the landlord files a dispossessory affidavit. The tenant has seven days from service to answer. After judgment, a writ of possession becomes effective seven days later. Even a smooth dispossessory takes weeks. A contested dispossessory takes longer.',
      'For tired landlords who want vacant possession before sale, the dispossessory timeline matters. A landlord who decides to sell in February but has to dispossess a tenant first might not have a vacant unit until April or May. During that window, no rent comes in (especially if the tenant has stopped paying), property taxes accrue, and the property continues to age.',
      'The alternative to vacant possession is selling with the tenant in place. Most Georgia leases survive a sale — the new owner becomes the new landlord. The lease terms continue. The tenant\'s security deposit transfers to the new owner at closing. The tenant gets a notice with the new landlord\'s contact information, but their day-to-day housing situation does not change.',
      'Selling tenant-in-place expands the buyer pool significantly. Investors looking for income-producing rentals are interested in occupied properties. Owner-occupant buyers are typically not — they want to move in. A tired landlord whose property would not show well to owner-occupants (because of age, condition, location, or current tenancy) often nets more from an investor sale than from a vacant traditional listing.',
      'The tax side of a Georgia rental sale deserves CPA review before contracting. Capital gains tax applies to the appreciation — the difference between the sale price and the property\'s adjusted basis. The basis is the original purchase price, plus capital improvements, minus the depreciation taken over the years of rental ownership.',
      'Depreciation recapture is the IRS\'s mechanism for taking back the tax benefit of depreciation when the property gets sold. Section 1250 of the Internal Revenue Code addresses real-estate depreciation recapture, currently taxed at a maximum federal rate of 25% on the recaptured amount. State income tax also applies.',
      'For landlords who want to defer the tax, a § 1031 like-kind exchange can roll the proceeds into another investment property without paying capital gains or recapture in the year of sale. The IRS rules under Treasury Regulation § 1.1031(k)-1 are firm: the seller has 45 days from the sale closing to identify a replacement property in writing, and 180 days from closing (or the seller\'s tax-return due date including extensions, whichever is earlier) to complete the replacement-property purchase.',
      'A 1031 exchange requires a qualified intermediary to be set up before the closing on the relinquished property. The intermediary holds the proceeds during the identification and acquisition periods. If the seller takes constructive receipt of the proceeds before the exchange completes, the deferral fails.',
      'For tired landlords who do not want to roll into another rental — often the case for someone exiting the rental business entirely — the tax bill is what it is. A CPA can model the actual numbers: capital gains rate, depreciation recapture, state tax, net of any installment-sale or other deferral options. The cost of the CPA consultation is generally less than the tax savings from optimizing the sale structure.',
      'Out-of-state cash-buying operations sometimes underestimate the tenant-in-place complexities of Georgia rentals. They make offers based on online comp data, encounter the tenancy details during due diligence, and back out at closing because the lease terms or tenant ledger surprise them. A real Georgia rental buyer reviews the lease and tenant ledger up front and prices accordingly.',
      'Some Georgia rentals add specific complications worth knowing about. Manufactured homes on permanent foundations require title-conversion review at closing if the home is still on a separate motor-vehicle title. USDA Rural Development-financed rentals have specific assumption or payoff procedures that the lender has to approve. HOA-restricted rentals (some HOAs cap rentals or require new owners to live in the property) require HOA-document review during due diligence. Vacation-rental-licensed properties (in cities that license short-term rentals) require specific transfer-of-license review.',
      'For Hunter Army Airfield military rentals, the federal Servicemembers Civil Relief Act provides specific protections to active-duty military tenants. A landlord cannot evict an active-duty military tenant for non-payment without a court order under specific procedures. Selling the property does not eliminate those protections — the new owner steps into the same shoes.',
      'A legitimate cash buyer for a Georgia rental property generally does several things consistently: reviews the lease and tenant ledger before contracting, accommodates tenant-in-place transactions without requiring vacant possession, accepts properties as-is with deferred maintenance, accommodates 1031-exchange timing if a qualified intermediary is set up, and pays standard closing costs without commissions.',
      'The decision about whether to sell a rental is rarely about market timing in the abstract. It is usually about the specific property, the specific tenant, and the specific landlord\'s life circumstances. A landlord who is approaching retirement, has had a major life change, or is simply burned out from years of property management has different priorities than a landlord doing tax planning around appreciation.',
      'For Georgia landlords in any of our service-area counties — Bulloch, Effingham, Chatham, Candler, Emanuel, Evans, or Toombs — the cash-sale path is available regardless of tenant status, property condition, or 1031 timing. The early call helps. We can usually run an offer based on a brief property description, a recent rent roll, and a few photos. The CPA conversation should happen in parallel.',
      'Before deciding to sell, many tired landlords benefit from a clean look at their actual rental P&L. The rent received minus mortgage, insurance, taxes, repairs, vacancies, property management, and time spent gives the actual return. Many landlords discover that their effective hourly rate after time costs is lower than they assumed. Others discover that the property is producing well and the source of frustration is one specific tenant or one specific maintenance backlog. The decision to sell versus continue should follow the analysis, not the frustration.',
      'Owner financing is sometimes a partial alternative to a cash sale. Under owner financing, the seller carries a note from the buyer and receives payments over time rather than a single lump sum at closing. This can spread the capital-gains tax across multiple years (installment-sale treatment under IRC § 453) and can produce a higher effective sale price. Owner financing requires the seller to act somewhat as a lender — accepting some risk of default. A real-estate attorney and CPA should both be involved before signing an owner-finance contract.',
      'For Georgia rentals participating in the Section 8 Housing Choice Voucher program, a sale to a non-participating buyer can affect the voucher. The new owner has to either continue the HUD voucher contract or notify HUD that the property is no longer participating. The tenant\'s voucher itself moves with the tenant, not the property — so a tenant in a Section 8 unit that gets sold to a non-participating owner may have to relocate. The Public Housing Authority handling the voucher can clarify the specific timeline and procedure for your county.',
      'Tenant-as-buyer scenarios are uncommon but possible. A long-term tenant who wants to buy the property can sometimes negotiate a sale directly with the landlord. The mechanics are simpler than a third-party sale because there is no marketing, no showings, and no transition. The challenges are usually financing — the tenant has to qualify for a mortgage in a typical sale, or accept owner financing from the seller. A real-estate attorney can structure a tenant-buyer transaction either way.',
      'The decision math for exiting a Georgia rental depends on several specific numbers: current cash flow after all expenses, current property value minus selling costs, the seller\'s tax position (basis, depreciation taken, marginal tax bracket), available alternatives (1031 exchange, owner financing, traditional listing with vacant possession), and the seller\'s personal circumstances (health, retirement timing, time available for landlord work). A two-hour conversation with a CPA before contracting often produces a clearer decision than weeks of independent thinking.',
      'Some Georgia tired-landlord exits work best as portfolio sales rather than individual property sales. A landlord with three to five rentals in the same county sometimes finds that a single buyer interested in the whole portfolio offers a slightly different math than three individual sales. Portfolio buyers typically pay slightly less per property in exchange for buying multiple at once. We have closed Southeast Georgia portfolio sales, including small portfolios of two to five rentals.',
    ],
  },
  {
    slug: 'tax-liens',
    label: 'Tax Liens / Tax Sale',
    shortLabel: 'Tax Liens',
    searchVerb: 'Resolve',
    triggers: [
      'Confusion about what a "tax-deed-purchaser" letter actually means — and whether the home is still theirs',
      'Fear of tax-deed investors showing up at the door demanding redemption money',
      'Worry that the 20% redemption premium is growing and the family cannot catch up',
    ],
    objections: [
      'Buyer who offers to "redeem on your behalf" but actually takes the deed without paying off the seller\'s other liens',
      'Buyer who does not know whether the property is in the redemption period or post-barment',
      'Tax-deed investor offering far below market because the homeowner thinks they have already lost the property',
    ],
    whatWeDo: [
      'Pay the redemption price plus mortgage payoff at closing so the seller walks away with clear title',
      'Close well before the barment deadline ends the right of redemption',
      'Coordinate with the county tax commissioner and tax-sale purchaser directly',
      'Refer the seller to a Georgia real-estate attorney to confirm redemption rights are still alive',
    ],
    ocgaRefs: [
      { code: 'OCGA § 48-4-40', summary: 'The defendant in fi.fa. or any party with a right, title, interest, or lien may redeem the property within 12 months of the tax sale.' },
      { code: 'OCGA § 48-4-42', summary: 'Redemption price equals the tax-sale amount plus a 20% premium for the first year and 10% for each year after, plus subsequent taxes and costs.' },
      { code: 'OCGA § 48-4-45', summary: 'After 12 months, the tax-sale purchaser can foreclose the right of redemption ("barment") by serving notice on the owner of record, occupant, and lienholders, and publishing in the legal-organ newspaper for four consecutive weeks.' },
    ],
    pillarLead: 'A Georgia tax sale does not immediately end ownership. For 12 months after the sale, the owner usually retains the right to redeem by paying the sale price plus a 20% premium. After that, the tax-deed buyer can begin the barment process — and only then does the right of redemption end.',
    pillarBody: [
      'Property tax problems in Georgia have a different rhythm than mortgage problems. The county tax commissioner — not the lender — drives the timeline. The applicable statutes are in OCGA Title 48, not OCGA Title 44. The sale itself happens at a different time, often in a different place, and gives the original owner rights that mortgage foreclosure does not.',
      'Most Georgia counties run scheduled tax sales rather than strict monthly first-Tuesday sales. Bulloch, Effingham, Evans, and Toombs all schedule tax sales as needed — sometimes a few times per year, sometimes irregularly. Chatham runs first-Tuesday tax sales but at the Savannah Civic Center rather than the courthouse, with online bidder registration. Candler runs only one tax sale per year — the first Tuesday in October — at the courthouse door in Metter. Emanuel runs irregular Tuesday sales on the courthouse steps in Swainsboro.',
      'The schedule variation matters because it means the timeline before a tax sale is rarely as predictable as the timeline before a mortgage foreclosure. A delinquent homeowner has to confirm with the county tax commissioner directly to know when the next sale is, and whether their property will be on it.',
      'The Georgia tax-sale process starts when property taxes go unpaid and the County Tax Commissioner issues a fi.fa. — short for fieri facias, a tax-execution document that authorizes a sale to satisfy the unpaid bill. The fi.fa. issues without a court hearing. Penalties and interest start accruing on the unpaid balance under Georgia law as soon as the bill is past due.',
      'Once a fi.fa. has issued and the property has been levied on, the tax sale gets advertised in the county\'s designated legal-organ newspaper for four consecutive weeks before the scheduled sale date. Each county uses a different paper — Statesboro Herald, Effingham Herald, Savannah Morning News, Metter Advertiser, Forest-Blade, Claxton Enterprise, The Advance.',
      'The sale itself happens by public outcry — the same kind of open auction that mortgage foreclosure sales use. A buyer who shows up at the sale (or registers online for Chatham) bids against other buyers. The high bidder receives a tax deed.',
      'Crucially, a tax deed is not fee-simple title yet. The original homeowner still has rights for a period after the sale. Georgia is one of a number of states with significant post-sale redemption protection.',
      'Under OCGA § 48-4-40, the original owner — or any party with a right, title, interest, or lien on the property — can redeem the property within 12 months of the tax sale by paying the redemption price. The redemption period is one of Georgia\'s most homeowner-friendly real-estate provisions. It gives a delinquent homeowner a year to recover the property after the sale.',
      'The redemption price under OCGA § 48-4-42 is set by statute. It equals the tax-sale amount plus a 20% premium for the first year, and 10% for each year after. Subsequent property taxes paid by the tax-deed buyer plus certain costs also get added on. The redemption price is not negotiable — the statute fixes it.',
      'For a homeowner with the cash to redeem, the math is straightforward. For one without the cash, the redemption period creates an opportunity to sell the property to a buyer who can pay the tax-deed buyer the redemption price plus any mortgage at closing. The original homeowner walks away with whatever equity remains.',
      'After 12 months, the tax-deed buyer can begin the barment process under OCGA § 48-4-45 to extinguish the original owner\'s right to redeem permanently. Barment requires serving notice on the owner of record, the occupant of the property, and any recorded interest holders, and publishing a notice in the county\'s legal-organ newspaper for four consecutive weeks. After the barment notice deadline expires, the right of redemption ends, and the tax-deed buyer\'s title ripens to fee-simple.',
      'Until barment is complete, the original homeowner retains the right to redeem. After barment, that right is gone. The window between the sale and the barment-notice deadline is the practical timeline for a homeowner to act if they want to recover the property — either by paying the redemption price directly or by selling to a buyer who pays it on their behalf.',
      'Tax sales are sometimes confused with mortgage foreclosures. They are different. Mortgage foreclosure (OCGA § 44-14-162) is run by the lender\'s attorney for unpaid mortgage payments. Tax-sale foreclosure (OCGA § 48-4) is run by the county tax commissioner for unpaid property taxes. The two have different timelines, different statutes, and different math.',
      'Both can run on the same property simultaneously. A homeowner who is behind on the mortgage and behind on property taxes may be facing both processes at the same time, on different schedules, with different paperwork. Both have to be resolved at any sale that produces clear title.',
      'For a homeowner who wants to sell during the pre-tax-sale period (after the tax bill is past due but before the actual sale), the math is simpler. The tax bill (plus penalties, interest, and any tax-sale advertising costs assessed) gets paid out of closing proceeds. The fi.fa. is satisfied. No tax sale ever runs.',
      'For a homeowner who wants to sell during the redemption period (after the tax sale but before barment is complete), the math involves paying the tax-deed buyer the OCGA § 48-4-42 redemption price (sale price plus 20% first-year premium plus subsequent additions) plus paying any mortgage holder. Both come out of closing proceeds. The redemption price plus mortgage usually still leaves equity for the seller — but not always.',
      'For a homeowner who has missed the barment deadline — and the right of redemption has ended — the property has typically passed to the tax-deed buyer\'s fee-simple ownership. At that point, no sale by the original owner is possible because they no longer hold title. The avenue closed.',
      'The county-specific procedural quirks matter. Bulloch\'s tax sales happen a few times a year and are advertised in the Statesboro Herald. Chatham\'s run at the Savannah Civic Center with online bidder registration. Candler\'s run once a year in October at the Metter courthouse door. Effingham\'s are scheduled by the Tax Commissioner without a strict cadence. Emanuel\'s run on irregular Tuesdays. Evans\'s schedule is not posted online — it has to be confirmed by phone. Toombs\'s delinquent list is published "in office only" — not online. Each county requires a different first phone call.',
      'Out-of-state buyers often get tax-sale logistics wrong. They confuse foreclosure sales with tax sales. They miss the redemption-period math. They underestimate how long a barment process takes. They send offer letters to homeowners weeks before a tax sale assuming the homeowner has no rights, when in fact the homeowner has the right to redeem for a year after the sale even if it does happen.',
      'A legitimate cash buyer for a Georgia property in tax-lien trouble generally does several things: confirms with the county tax commissioner directly the exact tax payoff and any pending sale schedule, reads any notices the homeowner has received to determine whether the timeline is pre-sale or post-sale or post-barment, coordinates the redemption-price calculation with a real-estate attorney if the property is in the redemption window, pays both the tax-deed buyer (if applicable) and any mortgage at closing, and refers to a real-estate attorney for any nuanced redemption-math review.',
      'For homeowners with property tax problems in any of our Georgia service-area counties — Bulloch, Effingham, Chatham, Candler, Emanuel, Evans, or Toombs — the early call matters. A pre-sale closing is almost always less expensive than a redemption-period closing. A redemption-period closing is almost always less expensive than letting the property pass to the tax-deed buyer through barment. The math gets harder the longer the situation continues.',
      'Reading the fi.fa. paperwork carefully matters. The document specifies the property by parcel ID, lists the unpaid tax amount, identifies the issuing tax commissioner office, and shows the date of issuance. The fi.fa. itself does not specify the tax-sale date — that comes later through advertising in the county legal-organ newspaper. A homeowner who receives fi.fa. paperwork has time to act before the actual sale, but the time varies by county and by how long the property has been delinquent. Bring the paperwork to a real-estate attorney for a quick read; the consultation is usually inexpensive and can clarify exactly where in the process you are.',
      'Georgia tax-deed buyers fall into several categories. Some are individual investors looking for distressed-property opportunities. Some are LLCs or corporations specializing in tax-deed acquisition. Some are speculative buyers who never plan to take the property — they are betting on redemption and the 20% premium that comes with it. Some are local property investors looking to add to their rental portfolios. Different buyer types behave differently when contacted about a redemption-period sale to a third party. Working with a real-estate attorney who has experience with tax-deed buyers in your specific county helps.',
      'Mortgages and tax sales interact in specific ways. A tax sale generally extinguishes the mortgage holder\'s lien on the property — the mortgage company loses its security interest if redemption does not happen. The mortgage company may pay the tax bill before the sale to protect its position, in which case the homeowner now owes the tax-amount-plus-protection-fees to the mortgage company. After a tax sale, the mortgage holder may exercise its own redemption right under OCGA § 48-4-40 to recover the property. These dynamics make the post-sale period complicated when both a mortgage and a tax-deed buyer are in the picture.',
    ],
  },
]

export function situationHref(slug: SituationSlug) {
  return `/situations/${slug}`
}

export function intersectionHref(citySlug: string, situationSlug: SituationSlug) {
  return `/areas/${citySlug}/${situationSlug}`
}

export const SITUATION_SLUGS: readonly SituationSlug[] = SITUATIONS.map(s => s.slug)
